mudskipper-dev-postgresql:
  container_name: mudskipper-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/mudskipper/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=mudskipper
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
