mudskipper-elasticsearch:
  container_name: mudskipper-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/mudskipper/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
mudskipper-postgresql:
  container_name: mudskipper-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/mudskipper/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=mudskipper
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
